### ISSUE TITLE
Figuring out rules and theme for the game

### ISSUE THREAD

**Issue by AhadKhan98** [vrushti-mody/Mini-Games#1]
We need a list of rules and some ideas for the theme of the game

**Comment by AhadKhan98** [comment]
**Idea to experiment with:**

- Clues that lead to figuring out who the imposters are

- Imposters have superpowers that they have to hide (walking through walls, shooting lasers etc)

**Comment by AhadKhan98** [comment]
Objectives: 

- Superheroes, Villians, and Civilians.
- Villains are going to try to kill civilians and superheroes.
- Civilians will help the superheroes in finding out who the villains are and defeat them.
- Superheroes are going to defeat/kill the villains.
- Both villains and superheroes have powers such as (walking through walls, speed boost, shooting lasers). However, villains should be more powerful since superheroes have additional help.

**Comment by vrushti-mody** [comment]
We have changed the game
